services:
  - type: web
    name: legalbuddy-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - fromGroup: legalbuddy-secrets
    ports:
      - 8000
    disks:
      - name: vector-db
        mountPath: /app/db_storage
      - name: chat-db
        mountPath: /app/data/processed

  - type: web
    name: legalbuddy-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile.frontend
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: ${legalbuddy-backend.url}
    ports:
      - 3501

envVarGroups:
  - name: legalbuddy-secrets
    envVars:
      - key: GROQ_API_KEY
        value: "gsk_..."
      - key: TAVILY_API_KEY
        value: "tvly-..."
      - key: DATABASE_URL
        value: "postgres://..."

  - type: job
    name: vector-store-builder
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: python -m src.vector_store
    envVars:
      - fromGroup: legalbuddy-secrets
    disks:
      - name: vector-db
        mountPath: /app/db_storage
      - name: chat-db
        mountPath: /app/data/processed
